# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: purple

# SEO
marketing:
  seo:
    site_type: Organisation
    local_business_type: ''
    org_name: "ReviewTemplate"
    description: "Beautiful Canva templates for book reviewers, bloggers, and influencers"
    twitter: 'reviewtemplate'
  analytics:
    google_analytics: 'G-XDCEQNV7Y1'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "ReviewTemplate"
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    button:
      enable: true
      text: "Shop Now"
      url: "https://reviewtemplate.gumroad.com/"
    show_search: true
    show_theme_chooser: true

# Site Footer
footer:
  copyright:
    notice: "© {year} ReviewTemplate. All rights reserved."
  links:
    - name: "Privacy Policy"
      url: "/privacy"
    - name: "Terms"
      url: "/terms"
    - name: "Contact"
      url: "/contact"

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Additional Important Settings
privacy:
  cookie_banner:
    enable: true
    content: "We use cookies for analytics. [Learn more](/privacy/)"
  google:
    analytics: true  # Required for GA4

services:
  email: "hello@reviewtemplate.com"
  social:
    - icon: "instagram"
      url: "https://instagram.com/reviewtemplate"
    - icon: "twitter"
      url: "https://twitter.com/reviewtemplate"
